import type { Metadata } from "next";
import localFont from "next/font/local";
import {SessionProvider} from "next-auth/react";
import NavBar from "@/components/navbar/nav-bar";
import { Slide, ToastContainer } from "react-toastify";
import { CartProvider } from "@/providers/cart-provider"
import {ReactQueryProvider} from "@/providers/reac-query-provider"
import "./globals.css";
import "react-toastify/dist/ReactToastify.css"


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  login,
  signup
}: Readonly<{
  children: React.ReactNode;
  login: React.ReactNode;
  signup: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <CartProvider>
          <ToastContainer
                    autoClose={3000}
                    closeOnClick
                    draggable
                    hideProgressBar={false}
                    newestOnTop
                    pauseOnFocusLoss
                    pauseOnHover
                    position='top-right'
                    toastClassName=' p-3 space-x-2 w-full'
                    transition={Slide}
                />
          <NavBar />
        <ReactQueryProvider>
          {children}
          {login}
          {signup}
         </ReactQueryProvider>
         </CartProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
